name: Slack Notification
on:
  push:
    branches:
      - master

jobs:
  slack-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 
        with:
          status: ${{ job.status }}
          text: Workflow has completed with status ${{ job.status }}!
          args: '{"text": "Changes have been made to the repository!"}'