name: Slack Notification
on:
  push:
    branches:
      - master

jobs:
  slack-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with:
          args: '{"text": "Changes have been made to the repository!"}'
